<?xml version="1.0" encoding="UTF-8"?>
<!--
/*********************************************************************
* Copyright (c) 2025 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdx" nsURI="http://www.eclipse.org/daanse/mdx/model" nsPrefix="mdx">
  <eClassifiers xsi:type="ecore:EClass" name="MdxStatement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for all MDX statements"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectStatement" eSuperTypes="#//MdxStatement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a SELECT statement in MDX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectWithClauses" upperBound="-1"
        eType="#//SelectWithClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectQueryClause" lowerBound="1"
        eType="#//SelectQueryClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectCubeClause" lowerBound="1"
        eType="#//SelectCubeClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectSlicerAxisClause"
        eType="#//SelectSlicerAxisClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectCellPropertyListClause"
        eType="#//SelectCellPropertyListClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrillthroughStatement" eSuperTypes="#//MdxStatement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a DRILLTHROUGH statement that retrieves underlying table rows"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstRowSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectStatement" lowerBound="1"
        eType="#//SelectStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnItems" upperBound="-1"
        eType="#//ReturnItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplainStatement" eSuperTypes="#//MdxStatement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an EXPLAIN statement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdxStatement" lowerBound="1"
        eType="#//MdxStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefreshStatement" eSuperTypes="#//MdxStatement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a REFRESH statement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeName" lowerBound="1"
        eType="#//NameObjectIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateStatement" eSuperTypes="#//MdxStatement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an UPDATE statement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeName" lowerBound="1"
        eType="#//NameObjectIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateClauses" upperBound="-1"
        eType="#//UpdateClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a return item in DRILLTHROUGH statement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compoundId" lowerBound="1"
        eType="#//CompoundId" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectWithClause" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for WITH clauses in SELECT statement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateMemberBodyClause" eSuperTypes="#//SelectWithClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a WITH MEMBER clause"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compoundId" lowerBound="1"
        eType="#//CompoundId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//MdxExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberPropertyDefinitions"
        upperBound="-1" eType="#//MemberPropertyDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateSetBodyClause" eSuperTypes="#//SelectWithClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a WITH SET clause"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compoundId" lowerBound="1"
        eType="#//CompoundId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//MdxExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateCellCalculationBodyClause" eSuperTypes="#//SelectWithClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a WITH CELL CALCULATION clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureBodyClause" eSuperTypes="#//SelectWithClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a WITH MEASURE clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberPropertyDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a member property definition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//MdxExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectIdentifier" lowerBound="1"
        eType="#//ObjectIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectQueryClause" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for SELECT query clauses"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectQueryAsteriskClause" eSuperTypes="#//SelectQueryClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a SELECT * clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectQueryAxesClause" eSuperTypes="#//SelectQueryClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a SELECT clause with multiple axes"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectQueryAxisClauses"
        lowerBound="1" upperBound="-1" eType="#//SelectQueryAxisClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectQueryEmptyClause" eSuperTypes="#//SelectQueryClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an empty SELECT clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectQueryAxisClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a single axis clause in a SELECT statement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonEmpty" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//MdxExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" lowerBound="1" eType="#//Axis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectDimensionPropertyListClause"
        eType="#//SelectDimensionPropertyListClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Axis">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an axis in a SELECT statement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="named" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectCubeClause" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for FROM clauses"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectCubeClauseName" eSuperTypes="#//SelectCubeClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a FROM clause with a cube name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeName" lowerBound="1"
        eType="#//ObjectIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectCubeClauseSubStatement" eSuperTypes="#//SelectCubeClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a FROM clause with a sub-SELECT statement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectSlicerAxisClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a WHERE (slicer) clause"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//MdxExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectCellPropertyListClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a CELL PROPERTIES clause"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cell" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectDimensionPropertyListClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a DIMENSION PROPERTIES clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an UPDATE clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an allocation in UPDATE statement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationAtom" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for all operation atoms"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmpersandQuotedPropertyOperationAtom"
      eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an ampersand-quoted property operation (object.[&amp;PROPERTY])"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BracesOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a braces operation ({ expression })"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a CASE operation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CastOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a CAST operation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an empty operation (e.g., FunctionOrMethod(1, ,3))"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a function operation (FUNCTION(), FUNCTION(args))"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfixOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an infix operation (arg OPERATOR arg)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an internal operation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a method operation (object.FunctionName())"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParenthesesOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a parentheses operation (arg, arg)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainPropertyOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a plain property operation (object.PROPERTY)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostfixOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a postfix operation (arg OPERATOR)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefixOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a prefix operation (OPERATOR arg)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuotedPropertyOperationAtom" eSuperTypes="#//OperationAtom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a quoted property operation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MdxExpression" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for all MDX expressions"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallExpression" eSuperTypes="#//MdxExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a call expression with an operation atom and arguments"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationAtom" lowerBound="1"
        eType="#//OperationAtom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//MdxExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" interface="true"
      eSuperTypes="#//MdxExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for all literal expressions"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//Literal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a NULL literal"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericLiteral" eSuperTypes="#//Literal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a numeric literal value"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a string literal value"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolLiteral" eSuperTypes="#//Literal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a symbol literal value"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundId" eSuperTypes="#//MdxExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a compound identifier consisting of multiple object identifiers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectIdentifiers" lowerBound="1"
        upperBound="-1" eType="#//ObjectIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIdentifier" abstract="true" interface="true"
      eSuperTypes="#//MdxExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for object identifiers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quoting" lowerBound="1"
        eType="#//QuotingEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QuotingEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration for quoting styles of identifiers"/>
    </eAnnotations>
    <eLiterals name="UNQUOTED"/>
    <eLiterals name="QUOTED" value="1"/>
    <eLiterals name="KEY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameObjectIdentifier" eSuperTypes="#//ObjectIdentifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a named object identifier"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyObjectIdentifier" eSuperTypes="#//ObjectIdentifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a key-based object identifier"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameObjectIdentifiers"
        lowerBound="1" upperBound="-1" eType="#//NameObjectIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormulaExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a formula expression"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
